[package]
name = "photoncube2video"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.9", features = ["derive", "cargo"] }
exitcode = "1.1.2"
ffmpeg-sidecar = "0.3.2"
glob = "0.3.1"
image = "0.24.5"
imageproc = "0.23.0"
indicatif = {version = "*", features = ["rayon"]}
itertools = "0.10.5"
natord = "1.0.9"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-npy = "0.8.1"
nshare = "0.9.0"
num-traits = "0.2.15"
rand = "0.8.5"
rayon = "1.7.0"
rusttype = "0.9.3"
tempfile = "3.4.0"

[profile.release]
lto = true

