[package]
name = "photoncube2video"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.9", features = ["derive", "cargo"] }
exitcode = "1.1.2"
image = "0.24.5"
imageproc = "0.23.0"
indicatif = {version = "*", features = ["rayon"]}
itertools = "0.10.5"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-npy = "0.8.1"
rayon = "1.7.0"
rusttype = "0.9.3"

[profile.release]
lto = true

