[package]
name = "photoncube2video"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
clap = { version = "4.4.18", features = ["derive", "cargo"] }
conv = "0.3.3"
exitcode = "1.1.2"
ffmpeg-sidecar = "0.5.1"
flate2 = "1.0.28"
glob = "0.3.1"
image = "0.24.8"
imageproc = "0.23.0"
indicatif = {version = "*", features = ["rayon"]}
itertools = "0.12.0"
memmap2 = "0.9.4"
natord = "1.0.9"
ndarray = { version = "0.15.6", features = ["rayon"] }
ndarray-npy = "0.8.1"
ndarray-stats = "0.5.1"
noisy_float = "0.2.0"
nshare = "0.9.0"
num-traits = "0.2.17"
rand = "0.8.5"
rayon = "1.8.1"
rusttype = "0.9.3"
tempfile = "3.9.0"

[profile.release]
lto = true

